### ISSUE TITLE
How to install and use MPI-parallel version of SSCHA?

### ISSUE THREAD

**Issue by Bingtan-Li** [SSCHAcode/python-sscha#100]
Is there any special parameter settings needed in setup.py or input.py?

**Comment by diegomartinez2** [comment]
On linux the command line for installing from source is if you have an administrator (root) account:

>  sudo python3 setup.py install

or if you want it only for your user:

> python3 setup.py install --user

In order to use the MPI implementation you need also to install MPI, on Debian/Ubuntu is:

> sudo apt-get install mpi

OpenMPI is installed with:

> sudo apt-get install openmpi-bin openmpi-common libopenmpi1.3 libopenmpi-dbg libopenmpi-dev

If you want to use remote computers or sending work to a cluster:

> sudo apt-get install openssh-client openssh-server

I hope this helps.

**Comment by Bingtan-Li** [comment]
Dear Diego,

Many thanks for your replying.

It is clear for me now.

Besides, there is a few more qusetions about MPI.

1. Compared to the version without MPI, how much more efficiently will MPI improve computing efficiency? Does it increase linearly with the number of kernels?

2. Is it true that all functions can use MPI to improve computing efficiency?

Best regards,
Bingtan Li

**Comment by diegomartinez2** [comment]
1. In computing, parallelization efficiency is not linear, see [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law). The best parallelization gives 1/N with N the number of cores, after that there is the data transmission bottleneck that reduces the efficiency.
2. Parallelization are best done in batches of independent calculations. There are functions that are intrinsically not parallelizables, like operations that require the knowledge of a previous step.

**Comment by Bingtan-Li** [comment]
I see. Thank you again.
