### ISSUE TITLE
The generated structural atoms are too closed

### ISSUE THREAD

**Issue by woyolo990422** [SSCHAcode/python-sscha#151]
I am calculating a 64 atom (4 × 4× 4) The supercell, with a temperature of 10000K, generates a structural displacement that is too large, resulting in some atoms being too far apart, resulting in a force that is too large for sscha to read properly.

**Comment by woyolo990422** [comment]
If I use the phonopy interface, I will have this problem. If I use phonon files directly calculated from QE, I will not have this problem

**Comment by mesonepigreco** [comment]
Hi, we have some issues with the phonopy interface. There is a bug in reading from phonopy. As a rule of thumb, always use the quantum espresso format to read the dynamical matrix.
