### ISSUE TITLE
Error compilation on HPC cluster

### ISSUE THREAD

**Issue by DromaninCM** [SSCHAcode/python-sscha#183]
Dear All,

I'm having trouble with the installation of python-sscha on a cluster (https://mesocentre.pages.centralesupelec.fr/user_doc/ruche/01_cluster_overview/). I'm doing this via conda.

I'm attaching the terminal output in which there are all the steps.

The compilation seems to end well, everything is installed and I can load both cellconstructor and sscha.
However, the problem is in SCHAModules as it is not seeing the thermodynamic attribute:

>>> sscha.Ensemble.SCHAModules.
sscha.Ensemble.SCHAModules.anharmonic(                     sscha.Ensemble.SCHAModules.get_gradient_supercell_fast(    sscha.Ensemble.SCHAModules.get_v3(
sscha.Ensemble.SCHAModules.cell_force(                     sscha.Ensemble.SCHAModules.get_gradient_supercell_new(     sscha.Ensemble.SCHAModules.get_v4(
sscha.Ensemble.SCHAModules.get_cmat(                       sscha.Ensemble.SCHAModules.get_odd_straight(               sscha.Ensemble.SCHAModules.get_ymu(
sscha.Ensemble.SCHAModules.get_emat(                       sscha.Ensemble.SCHAModules.get_odd_straight_with_v4(       sscha.Ensemble.SCHAModules.multiply_lambda_tensor(
sscha.Ensemble.SCHAModules.get_fmunu(                      sscha.Ensemble.SCHAModules.get_stress_tensor(              sscha.Ensemble.SCHAModules.stochastic(
sscha.Ensemble.SCHAModules.get_g(                          sscha.Ensemble.SCHAModules.get_unpreconditioned_gradient(  
sscha.Ensemble.SCHAModules.get_gradient_supercell(         sscha.Ensemble.SCHAModules.get_upsilon_matrix(           

Do you have any suggestion on how to solve it?

Best,

Davide

[Output_terminal_SSCHA_install.txt](https://github.com/SSCHAcode/python-sscha/files/13988118/Output_terminal_SSCHA_install.txt)

**Comment by DromaninCM** [comment]
I would also like to add that in the output you can see that it is performing all of the fortran compilation for the SCHAModule but when it comes to the thermodynamic it says:

                Constructing F90 module support for "thermodynamic"...
                        Skipping thermodynamic since it is in 'use'...

**Comment by diegomartinez2** [comment]
Looks like issue #184 is the same as this.

**Comment by mesonepigreco** [comment]
In #184 there is a proposed solution by Diego Martinez.
@DromaninCM , can you check if it fixes your problem on the cluster? If it does, we can do a patch and add it for the next release (maybe a new 1.4.1 to fix things quickly)

**Comment by mesonepigreco** [comment]
The discussion on #184 has been solved, there is a patch discussed there for this issue.
