### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by utf** [SSCHAcode/python-sscha#77]
Hi,  Thanks for developing this very useful code.

I've noticed there isn't a LICENSE file in the repository. Can you clarify the license of the project? Is it GPL v3 like cell constructor?

Thanks!

**Comment by mesonepigreco** [comment]
Hi, thanks for spotting this issue, yes it is the same license as cellconstructor, GPL v3

**Comment by utf** [comment]
Great, thanks for clarifying.
